new MonPoké = {
    id: 153,
    nom: 'Macronium',
    Type: 'plante',
    Poids: 15.8,
    mignonitude: 100,
    
  };
  
new MonPoké = {
    nom: 'Herbizarre',
    Type: 'plante',
    Poids: 13,
    mignonitude: 60,
    
  };

new MonPoké = {
    nom: 'Gobou',
    Type: 'eau',
    Poids: 	7.5,
    mignonitude: 80,
    
  };

  new MonPoké = {
    nom: 'Togekiss',
    Type: 'vol',
    Poids: 38,
    mignonitude: 75,
    
  };

  new MonPoké = {
    nom: 'Yanmega',
    Type: 'vol',
    Poids: 51.5 ,
    mignonitude: 75,
    
  };
  

  new MonPoké = {
    nom: 'Galvagon',
    Type: 'vol',
    Poids: 190 ,
    mignonitude: 45,
    
  };